language: node_js
node_js:
  - "12.6"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add bookmark-ui/@angular/cli

cache:
  yarn: true
  directories:
    - bookmark-ui/node_modules

script:
  - npm run lint
  - ng test --watch=false
  - ng build --prod --base-href https://Avinash1604.github.io/bookmark-ui/

after_success:
  - cat ./bookmark-ui/coverage/bookmark-ui/lcov.info | ./bookmark-ui/node_modules/coveralls/bin/coveralls.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./bookmark-ui/dist/
  on:
