
CREATE TABLE IF NOT EXISTS T_URL(
   ID INTEGER PRIMARY KEY,
   LONG_URL varchar(50000),
   EXPIRY_DATE DATE,
   TITLE varchar(150),
   DESCRIPTION varchar(1000),
   IS_BOOKMARK BOOLEAN,
   CREATED_ON TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS T_URL_SEQUENCE START 100;

CREATE TABLE IF NOT EXISTS T_USER(
   USER_ID INTEGER PRIMARY KEY,
   USER_NAME varchar(256),
   PASSWORD varchar(256),
   EMAIL varchar(200),
   CREATED_ON TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS T_USER_SEQUENCE START 1;


CREATE TABLE IF NOT EXISTS T_GROUP(
   GROUP_ID INTEGER PRIMARY KEY,
   GROUP_NAME varchar(256),
   GROUP_URL varchar(256),
   CREATED_ON TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS T_GROUP_SEQUENCE START 1;


CREATE TABLE IF NOT EXISTS T_ROLE(
   ROLE_ID INTEGER PRIMARY KEY,
   ROLE_NAME varchar(256));

CREATE TABLE IF NOT EXISTS T_GROUP_USER(
   ID INTEGER PRIMARY KEY,
   GROUP_ID INTEGER,
   USER_ID INTEGER,
   USER_NAME varchar(256),
   EMAIL varchar(200),
   ROLE_NAME varchar(256),
   CREATED_ON TIMESTAMP,
   CONSTRAINT fk_T_GROUP
    FOREIGN KEY(GROUP_ID)
   	  REFERENCES T_GROUP(GROUP_ID)
   	  ON DELETE SET NULL
   );

CREATE SEQUENCE IF NOT EXISTS T_GROUP_USER_SEQUENCE START 1;


CREATE TABLE IF NOT EXISTS T_GROUP_URL(
   ID INTEGER PRIMARY KEY,
   GROUP_ID INTEGER,
   LONG_URL varchar(50000),
   EXPIRY_DATE DATE,
   TITLE varchar(150),
   DESCRIPTION varchar(1000),
   CREATED_ON TIMESTAMP,
   CONSTRAINT fk_T_GROUP
    FOREIGN KEY(GROUP_ID)
   	  REFERENCES T_GROUP(GROUP_ID)
   	  ON DELETE SET NULL
   );

CREATE SEQUENCE IF NOT EXISTS T_GROUP_URL_SEQUENCE START 1;










