
CREATE TABLE IF NOT EXISTS T_URL(
   ID INTEGER PRIMARY KEY,
   LONG_URL varchar(50000),
   EXPIRY_DATE DATE,
   TITLE varchar(150),
   DESCRIPTION varchar(1000),
   IS_BOOKMARK BOOLEAN,
   CREATED_ON TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS T_URL_SEQUENCE START 100;

CREATE TABLE IF NOT EXISTS T_USER(
   USER_ID INTEGER PRIMARY KEY,
   USER_NAME varchar(256),
   PASSWORD varchar(256),
   EMAIL varchar(200),
   CREATED_ON TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS T_USER_SEQUENCE START 1;
